version: "3.7"
services:
  database:
    image: mysql:8.0
    restart: unless-stopped
    container_name: ${APPLICATION_NAME}_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_USER_ROOT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      #- ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_app:/var/lib/mysql
    ports:
      - ${DB_PORT_LOCAL}:${DB_PORT}
volumes:
  mysql_app:
